name: Docker

on: [ push, pull_request, workflow_dispatch ]


jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run the Docker image
        run: |
          docker compose up -d --wait